Traceback (most recent call last):
  File "/home/sidn/puma/grapple/scripts/training/papu/train_pu.py", line 24, in <module>
    ('--opt'),
TypeError: 'tuple' object is not callable
